#!/bin/bash

DB_HOST="localhost"
DB_NAME="Mongo"
DB_PORT=3306
DB_USER="Bolvic"
DB_USER_PWD="goserv"
DB_MIN_POOL_SIZE=0
DB_MAX_POOL_SIZE=10
DB_QUERY_TIMEOUT_SEC=5

echo "Installing database..."


echo "Starting temp server"
mysqld --user=root &
MARIADB_PID=$?


echo "Mariadb is starting..."
mariadb-check -A
STATUS=$?
while [[ $STATUS -ne 0 ]]
do
	mariadb-check -A
	STATUS=$?
	sleep 1
done

echo "Creating user and database"
mariadb << EOF
CREATE USER $DB_USER@'$DB_HOST' IDENTIFIED BY "$DB_USER_PWD";
CREATE DATABASE $DB_NAME;
GRANT ALL PRIVILEGES on $DB_NAME.* to $DB_USER@'$DB_HOST';
FLUSH PRIVILEGES;
SELECT User,Host FROM mysql.user;
EOF


echo "Stoping temp server"
kill $MARIADB_PID
wait $MARIADB_PID

echo "Installation complete"

exit 0
