# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb:
    container_name: mariadb
    networks:
      - scraver 
    build: ./mariadb
    env_file: .env
    volumes: 
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  goserve:
    container_name: goserve
    networks:
      - scraver
    depends_on:
      - mariadb
    build: ./
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/mariadb'

networks:
  scraver:
     driver: bridge
