version: '3.1'

services:


  mariadb:
    container_name: mariadb
    networks:
      - scraver 
    build: ./mariadb
    env_file: ./app/.env
    volumes: 
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  goserve:
    container_name: goserve
    networks:
      - scraver
    depends_on:
      - mariadb
    ports:
      - "443:443"
      - "80:80"
    build: ./app
    env_file: ./app/.env
    restart: on-failure

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/mariadb'

networks:
  scraver:
     driver: bridge
